name: "Fintech Specialization"
version: "1.0.0"
description: "Financial technology industry specialization with compliance and risk management"

# Specialization metadata
metadata:
  industry: "Financial Technology"
  compliance_frameworks:
    - "PCI-DSS"
    - "SOX"
    - "GDPR"
    - "MiFID II"
    - "Basel III"
    - "FATCA"
    - "KYC"
    - "AML"
  risk_categories:
    - "Market Risk"
    - "Credit Risk"
    - "Operational Risk"
    - "Compliance Risk"
    - "Cybersecurity Risk"
    - "Liquidity Risk"

# Enhanced ethics constraints for financial services
ethics:
  financial_services_constraints:
    - constraint: "customer_protection"
      description: "Always prioritize customer protection and fair treatment"
      severity: "critical"
      validation: "ensure_customer_benefit"
    
    - constraint: "regulatory_compliance"
      description: "All actions must comply with applicable financial regulations"
      severity: "critical"
      validation: "check_regulatory_requirements"
    
    - constraint: "market_integrity"
      description: "Maintain market integrity and prevent manipulation"
      severity: "critical"
      validation: "verify_market_fairness"
    
    - constraint: "data_privacy"
      description: "Protect customer financial data and maintain privacy"
      severity: "critical"
      validation: "ensure_data_protection"
    
    - constraint: "conflict_of_interest"
      description: "Avoid conflicts of interest in financial advice"
      severity: "high"
      validation: "check_conflict_independence"

# Enhanced safety thresholds for financial operations
safety:
  financial_thresholds:
    transaction_limits:
      single_transaction_max: 1000000  # $1M
      daily_volume_max: 10000000       # $10M
      velocity_threshold: 100          # transactions per minute
    
    risk_metrics:
      portfolio_var_limit: 0.05        # 5% Value at Risk
      concentration_limit: 0.20        # 20% single position limit
      leverage_ratio_min: 0.03         # 3% minimum leverage ratio
    
    system_performance:
      latency_max_ms: 100              # 100ms max latency for trading
      uptime_requirement: 0.9999       # 99.99% uptime requirement
      error_rate_max: 0.001            # 0.1% max error rate

# Resource allocation for financial workloads
resource_allocation:
  trading_systems:
    cpu_cores: 8
    memory_gb: 32
    storage_gb: 500
    network_bandwidth_mbps: 1000
    priority: "high"
  
  compliance_processing:
    cpu_cores: 4
    memory_gb: 16
    storage_gb: 1000
    priority: "medium"
  
  risk_analytics:
    cpu_cores: 16
    memory_gb: 64
    storage_gb: 2000
    gpu_enabled: true
    priority: "high"

# Audit requirements
audit:
  retention_periods:
    transaction_logs: "7_years"
    compliance_reports: "7_years"
    customer_communications: "5_years"
    risk_assessments: "3_years"
    system_logs: "1_year"
  
  required_fields:
    - "timestamp"
    - "user_id"
    - "transaction_id"
    - "amount"
    - "currency"
    - "counterparty"
    - "risk_score"
    - "compliance_status"
    - "approval_chain"

# Integration settings
integrations:
  risk_systems:
    - "market_data_providers"
    - "credit_bureaus"
    - "fraud_detection_services"
    - "regulatory_databases"
  
  compliance_systems:
    - "kyc_providers"
    - "sanctions_screening"
    - "transaction_monitoring"
    - "regulatory_reporting"
  
  trading_systems:
    - "order_management_systems"
    - "execution_platforms"
    - "settlement_systems"
    - "market_data_feeds"