version: '3.8'

# Development override for docker-compose.control.yml
# Usage: docker-compose -f docker-compose.control.yml -f docker-compose.dev.yml up

services:
  control-layer:
    build:
      context: ../control
      dockerfile: Dockerfile
      target: builder  # Use builder stage for development
    
    # Development environment
    environment:
      - CONTROL_ENV=development
      - LOG_LEVEL=DEBUG
      - RELOAD=true
      - DEBUG=true
    
    # Mount source code for hot reload
    volumes:
      - ../control:/app/control
      - control-storage:/app/control/storage
      - control-logs:/app/control/logs
    
    # Development command with auto-reload
    command: ["uvicorn", "api:app", "--host", "0.0.0.0", "--port", "8000", "--reload", "--log-level", "debug"]
    
    # Remove some production constraints
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
    
    # Skip health check in development
    healthcheck:
      disable: true
    
    # No dependencies in dev mode
    depends_on: []

  # Simplified Redis for development
  redis:
    ports:
      - "6379:6379"
    environment:
      - REDIS_DISABLE_COMMANDS=

  # Simplified PostgreSQL for development
  postgres:
    environment:
      POSTGRES_DB: control_db_dev
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    ports:
      - "5432:5432"

  # No nginx in development
  nginx:
    profiles:
      - production